apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/project-f2995e59-f5d2-491f-ba8/lab-mvn-design/binarycalculator
          imagePullPolicy: Always
          name: binarycalculator
          ports:
            - containerPort: 8080
              name: http
